### ISSUE TITLE
Improvement of the Eclipse Research website

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/eclipse.org-research#2]
From https://foundation.eclipse.org/infrazilla/show_bug.cgi?id=3528#c15

On the week of January 13 we had a meeting to discuss the changes to the research page.

Here are @ericpoirier notes:

- Create hugo website (DONE)
- Redesign the following sections:
    - Projects
        - Similar to Jakarta EE Projects page
        - Include badges to highlight Eclipse Projects
    - Success story
- Create Research projects page which will contains sub projects
- Ask Wayne if we can use a “Research” keyword or tag in the PMI to categorize Research projects

Target: March 2020

**Comment by phkrief** [comment]
Hi @ericpoirier  and @chrisguindon 

I was wondering if you had the chance to make some progress on the new design of the web pages. Actually, we start getting pressure from a project and I would like to try the new design on it to reassure them.

thanks a lot
Kind regards
-Philippe

**Comment by chrisguindon** [comment]
Hi Phillippe, 

We are planning to start working on this next week.

We have quite a lot on out plate right now but my hope is that we can make some good progress next week.

**Comment by phkrief** [comment]
Hi Chris,

Thanks for your quick reply.
Does it mean that I can expect to have the new version running by the end
of the month as initially planned?
Thanks

-Philippe

**Comment by chrisguindon** [comment]
@phkrief, This is the plan :)

Finally, I've asked Martin to start working on the projects pages today.

@autumnfound Please review these documents:

1. Project Briefing from research team: https://docs.google.com/presentation/d/17NdV51ss9FOvpwRlrj4FCOYYg4PhMEDSOPM26e-F0WM/edit#slide=id.g75bd5ce0b3_0_154

2. Content:
https://docs.google.com/document/d/1uRKVAg2QszvqBYc5RhuYxkJju--So8Jz8IqqP3M9DPI/edit#heading=h.mrf7uww1ok9

@ericpoirier already made all the content update from that page!

Summary:

1. Create a new project archetype:

1.1 logo: 
1.2 social_media_links: (twitter, youtube, website, linkedin, newsletter)
1.3 List of funding bodies:
1.4 List of related Eclipse working groups 
1.5 List of related Eclipse projects 

* I am thinking that we should create a data file for funding bodies and working groups so that we can reference them by an id to avoid duplicating data.

2. Update homepage:
2.1 Create an archetype/section for each Success story. A success story is usually the Eclipse projects that originated from a research project. 
2.2 Redesign how success stories and projects are displayed on the page:

I am thinking that we can leverage the tile look and feel on our Eclipse our working group page:  https://www.eclipse.org/org/workinggroups/explore.php

3.2 Create a  list of /projects page

This page should list both all research and Eclipse projects but we need to identify which are Eclipse projects. It was discuss to add a bootstrap badge to mark them.


@phkrief I am missing any other requirements? If i am not mistaken, we decided to drop the carrousel?

**Comment by phkrief** [comment]
Hi Chris 

I'm not sure to understand all your points. 
I really like the idea of these WG tiles that we could reuse for each Research project (successful or running). We should have actually 3 sections:
- one section for running research projects 
- one section for successful research projects 
- one section for friend research projects 

All these sections should have the same look&feel using this Tile template. 
Each tile should point to the corresponding Research project page. 
Each research project page should be described by a set of fields listed by Chris. + short description used for the time + long description used for the page. 

BTW, there is only one funding body per project. 

I don't understand your point 3.2.

In any cases, each research project page will stay there forever as a research project. The difference between a running research project and a successful or friend research project is that the 2 last might have one or more linkd pointing to the resulting Eclipse projects.

Does it make sense?

Thx

Le 11 mars 2020 à 15:33, à 15:33, Christopher Guindon <notifications@github.com> a écrit:

**Comment by chrisguindon** [comment]
>  We should have actually 3 sections:
> - one section for running research projects
> - one section for successful research projects
> - one section for friend research projects

Based off your document (https://docs.google.com/presentation/d/17NdV51ss9FOvpwRlrj4FCOYYg4PhMEDSOPM26e-F0WM/edit#slide=id.g75bd5ce0b3_0_154), we have 2 types of projects:

1. Research projects
2. Success stories which are basically Eclipse projects that originated from a research project. At the very least, this is how I understand it.

We can definitely add a "state" params to each of the research project to identify those that are done and those that are on-going.

> All these sections should have the same look&feel using this Tile template.

+1

> Each tile should point to the corresponding Research project page.

+1

> Each research project page should be described by a set of fields listed by Chris. + short description used for the time + long description used for the page.

Where can we find the long description? Most of the content in https://docs.google.com/document/d/1uRKVAg2QszvqBYc5RhuYxkJju--So8Jz8IqqP3M9DPI/edit# has a read more button. Do we have another document for all the text that we need for each research project page?

> BTW, there is only one funding body per project.

This is good to know! Thanks!

> I don't understand your point 3.2.

My understanding is that we needed a list of project page similar to https://jakarta.ee/projects/ which would include research projects and success stories. 

> In any cases, each research project page will stay there forever as a research project. The difference between a running research project and a successful or friend research project is that the 2 last might have one or more linkd pointing to the resulting Eclipse projects.

Perhaps we simply need to show success stories on the homepage and we only list research projects under our new /projects page?

Please advise on how to proceed!

**Comment by autumnfound** [comment]
@phkrief here is a couple links to our current progress!

https://deploy-preview-5--eclipsefdn-research.netlify.com/project/
https://deploy-preview-5--eclipsefdn-research.netlify.com/project/appstacle/

We'll still be working on look and feel going forward, but we wanted to rough in some content to get early feedback on the progress. I'll be spending some time tomorrow working on smoothing out some of the minor issues that exist in our current look and feel.

**Comment by phkrief** [comment]
Each research project page should be described by a set of fields listed by
> Chris. + short description used for the time + long description used for
> the page.
>


> Where can we find the long description? Most of the content in
> https://docs.google.com/document/d/1uRKVAg2QszvqBYc5RhuYxkJju--So8Jz8IqqP3M9DPI/edit# has
> a read more button. Do we have another document for all the text that we
> need for each research project page?

> this text will certainly be extracted either from the project website
like agile-iot.eu or crossminer.eu or from some written document or ...

> We, the research team, will create and maintain these pages. Not you. It
is, for this reason, we are asking for a template-based website
architecture. So, for each project we can either have one single text with
a more banner in the middle and use the first part of the text for the
tiles and the rest for the project page or we can have 2 texts. IMHO, I
think the first option is the easiest one. I already tried for blogpost in
hugo and it works great

We should have actually 3 sections:
>
>    - one section for running research projects
>
>
>    - one section for successful research projects
>
>
>    - one section for friend research projects
>
> Based off your document (
> https://docs.google.com/presentation/d/17NdV51ss9FOvpwRlrj4FCOYYg4PhMEDSOPM26e-F0WM/edit#slide=id.g75bd5ce0b3_0_154),
> we have 2 types of projects:
>
>    1. Research projects
>
>
>    1. Success stories which are basically Eclipse projects that
>    originated from a research project. At the very least, this is how I
>    understand it.
>
> We can definitely add a "state" params to each of the research project to
> identify those tat are done and those that are on-going.

You are correct. This need showed up late so I didn't want to bother you
with it so when I wrote the doc I didn't mention it and said that we will
take care of it.

I don't understand your point 3.2.
> My understanding is that we needed a list of project page similar to
> https://jakarta.ee/projects/ which would include research projects and
> success stories.
> In any cases, each research project page will stay there forever as a
> research project. The difference between a running research project and a
> successful or friend research project is that the 2 last might have one or
> more linkd pointing to the resulting Eclipse projects.
> Perhaps we simply need to show success stories on the homepage and we only
> list research projects under our new /projects page?
> Please advise on how to proceed!

Each project has the same level of importance: success stories like running
projects. So I will prefer to keep all of them on the same page and have
maybe 3 buttons to skip from one section to another one.

Should we have a quick call with you guys to clarify all these points? Thx

Kind regards
*—*
Philippe Krief,

**Comment by autumnfound** [comment]
@phkrief I'd be willing to do a call if you think it would help sure! I'm just making additional changes (such as splitting the projects into running, research, and friend projects) right now.

**Comment by autumnfound** [comment]
@phkrief here is the current template/archetype file:

```
---
title: "{{ replace .TranslationBaseName "-" " " | title }}"
date: {{ .Date }}
logo: ""
tags: []
homepage: ""
facebook: ""
linkedin: ""
twitter: ""
youtube: ""
funding_bodies: []
eclipse_projects: []
project_type: running
---
```

**Comment by autumnfound** [comment]
@phkrief One thing I realized is that there is an easier way to set the summary than having to dance around what is shown on the main page. If you set `summary: "Your summary text here"` in your content metadata above, it can be easily picked up and written, likely in a more clean fashion than using the in content text stuff I was talking about.

**Comment by autumnfound** [comment]
@phkrief I've updated the home page with my current progress. For the carousel, what kind of calls to action are you planning on using for it? Carousels can be kind of hard to read at times, as they are either too fast or too slow and people won't be able to consume the content.

I've also done most of the requested changes on the other pages, so please let me know if theres something with the layout that looks off/wrong, or would like tweaked in some way!

**Comment by phkrief** [comment]
@autumnfound please forget the carousel. It was mentioned in a previous call, we will not use a carousel to show our main value propositions. Thx

**Comment by phkrief** [comment]
@autumnfound I could install and setup your last version ! I **LOVE** the home page !!!

We could try to force the same height on each logo like that the names of the projects will be aligned. We also could reduce the size of the name knowing in most of the cases, the name is already visible in the logo. WDYT?

I'm not convinced about the project pages. I know it is what we suggested but, I don't like the current result. We should imagine a better layout. Any suggestions?

Thx a lot for your great work!!!

**Comment by autumnfound** [comment]
@phkrief I've updated the intro section with a couple of potential replacements for the carousel. The first is the link in the jumbotron. Second is the tiles section which rearranges itself as you shrink the page to be visible and easy to read. The third is just a refresh of the content you previously had with the same callout to a separate page. WDYT?

For the text size, I could shrink the project name text by about 50%, and I can look at matching the height across the different logos, but it might be a nice to have we add after this goes live if it proves to be more involved.

Whats your current issue with the layout? Knowing more about what you find off about it, we might be able to come up with some small tweaks to make it more visibly appealing.

**Comment by phkrief** [comment]
Hey @autumnfound ,
I cannot find your branch anymore. Where did you hide it ? ;-)
Thanks

**Comment by chrisguindon** [comment]
@phkrief The current work in progress is available here: https://deploy-preview-5--eclipsefdn-research.netlify.com/

**Comment by phkrief** [comment]
Hey @autumnfound , thx for the update
My comments:
- Please combine both options for the value proposition into one:
![image](https://user-images.githubusercontent.com/6196602/76790220-b9fc7a80-67be-11ea-850e-35d1d6351205.png)

- The project Tiles are definitively too high. I suspect they will be smaller once we will use a short sentence or a tagline instead of a summary. Right?

- Could you make the logo the same height, like that the name of the projects will be automatically aligned?

Thx a lot for your work

**Comment by autumnfound** [comment]
1. Can do! What are your thoughts on the icons? I made best guess at what would fit each section, but those can be changed to other icons available on https://feathericons.com/ if you'd like
1. For the most part yes, project tiles will shrink when you have shorter summaries. I did best guess to get the text down to a reasonable size. I can look at shrinking them a little more by making the logo space a little smaller if you like?
1. This might be a little more work to get done, so I can take a crack but it might fall to a post launch fix if its a more involved change. If it is, I'll create an issue to track the requirement.

**Comment by autumnfound** [comment]
@phkrief I've done some small updates and finished the changes up to now. I fixed the issue with the summaries being really long. We were building with an older version that treated summaries differently. https://deploy-preview-5--eclipsefdn-research.netlify.com/

**Comment by phkrief** [comment]
Hi @autumnfound, for the logos on sustainability, Guidance, ... are you limited? Can you tell us where you found them. We could find others that match better the idea behind. WDYT?
thx

**Comment by autumnfound** [comment]
> Hi @autumnfound, for the logos on sustainability, Guidance, ... are you limited? Can you tell us where you found them. We could find others that match better the idea behind. WDYT?
> thx

Please see the following: 
> 1. Can do! What are your thoughts on the icons? I made best guess at what would fit each section, but those can be changed to other icons available on https://feathericons.com/ if you'd like

**Comment by phkrief** [comment]
I forgot about your previous comment. Sorry.
I checked those icons. :-( Do we have other possible icons?
Else here are some suggestions:

For sustainability, we could use 'thumbs-up'
For guidance, we could use 'corner-up-right'
For Eclipse Ecosystem, we could use 'volume-2'

thx a lot

**Comment by autumnfound** [comment]
No worries! We could make use of other things but they wouldn't be the same theme or look and feel and would be a little disjointed. If you don't like these options we could look at it.

**Comment by phkrief** [comment]
No worries... This is really good enough...

**Comment by phkrief** [comment]
@hansmuff2 added

**Comment by autumnfound** [comment]
We've pushed the current work to a separate branch on this repo rather than in my own fork. If you would like to contribute @hansmuff2, please submit a PR against that branch

**Comment by phkrief** [comment]
I"m lost. I made a commit but I don't understand how I should push it back to your branch knowing I took the files from your branch...
Can you help me fix that?
Thx
![image](https://user-images.githubusercontent.com/6196602/77593412-6f80a980-6ef4-11ea-826a-1571fba8210b.png)

**Comment by chrisguindon** [comment]
@phkrief The best way would be to fork the repository and to push your branch there! 

Once that's done, you will be able to create a PR by visiting the homepage of this repo or your fork. 

When creating, your PR please make sure to chose to choose malowe/master/2 as your base.

I also included some documentation in the readme:
https://github.com/EclipseFdn/eclipse.org-research#contributing

Please let me know if you have any problems and we can schedule some time tomorrow for me to walk you through the steps!

**Comment by chrisguindon** [comment]
I think we are done here!

Closing this issue! Thank you @autumnfound, @phkrief and @hansmuff2

**Comment by phkrief** [comment]
Indeed !!! Thank so much guys for your GREAT work and support !!!
