### ISSUE TITLE
Jumbotron updates to https://www.eclipse.org/org/research/

### ISSUE THREAD

**Issue by ChristieWittEclipse** [EclipseFdn/eclipse.org-research#26]
Please make the following updates to https://www.eclipse.org/org/research/ (Mockup is attached):

-Add text in jumbotron header "Upcoming Conference: Eclipse SAM IoT 2020"
-Add button in jumbotron header "Download call for papers" with a link to https://events.eclipse.org/2020/sam-iot/sam-iot-cfp.pdf
-Update the Jumbotron background image to https://www.eclipse.org/eclipse.org-common/themes/solstice/public/images/vendor/eclipsefdn-solstice-components/landing-well/eclipse_home_bg.jpg

![UXPin-Jumbotron_options](https://user-images.githubusercontent.com/58480647/84040704-ef090b00-a970-11ea-9517-67396049f862.jpg)

**Comment by autumnfound** [comment]
Currently, we don't support multi line bodies in the jumbotron. There are 2 ways we can implement this in the current scope, both with their own downsides that can be somewhat mitigated. The second text section is a header, so it will appear to screen readers as a heading and is by nature larger. 

## Option 1
Flip the text. This means the event gets registered as a heading which is a little more "sensible" in page flow.
![image](https://user-images.githubusercontent.com/23018241/84049411-6b541c00-a97a-11ea-9e05-72b4391f9944.png)

## Option 2
Put the current normal text in as a header. This means that we have a really long bit of text as a heading which will be weird for screen readers and could be a little confusing. We could shrink it down to make it look more like the other text, but it would still register as a heading.
![image](https://user-images.githubusercontent.com/23018241/84049399-655e3b00-a97a-11ea-9836-17d666991d80.png)


Do either of these options work for you?

**Comment by ChristieWittEclipse** [comment]
@autumnfound thanks, option 2 is ideal. Is it possible to shrink the size of the "Business-friendly..." text 2 pixels?

**Comment by autumnfound** [comment]
@ChristieWittEclipse https://deploy-preview-27--eclipsefdn-research.netlify.app/ does that look good? Want to make sure before we merge in

**Comment by ChristieWittEclipse** [comment]
@autumnfound I would shrink the text a bit more so that it fits on 2 lines:
.jumbotron h2 {
    font-size: 27px;
}
Thanks!

**Comment by Ioana240** [comment]
Hi everyone,

as per Philippe's request, could you please delete the button for the conference and the title of the conference in the banner section on https://www.eclipse.org/org/research/?

Many thanks!

Cheers,
Ioana

**Comment by chrisguindon** [comment]
@Ioana240 What do you mean? You would like us to revert this work?

**Comment by Ioana240** [comment]
Hi @chrisguindon yes, we should revert this work. There has been a misunderstanding. Apologies for the inconvenience.

Thank you,
-Ioana
