### ISSUE TITLE
Changes to make before the redesign

### ISSUE THREAD

**Issue by phkrief** [EclipseFdn/eclipse.org-research#3]
To let the IT team quietly redesign our research website, we will appreciate  if you could reorganize the current list of research projects has it is described in the following document: 

https://docs.google.com/document/d/1uRKVAg2QszvqBYc5RhuYxkJju--So8Jz8IqqP3M9DPI/edit#heading=h.mrf7uww1ok9

I hope this is enough to help you.
Please keep me posted

**Comment by chrisguindon** [comment]
@phkrief,

@ericpoirier pushed up a PR for this issue, you can review the changes here:
https://deploy-preview-4--eclipsefdn-research.netlify.com/

**Comment by phkrief** [comment]
Looks great to me! Thanks a lot @ericpoirier and @chrisguindon .

I will ask Susan and Marco to review as well...

**Comment by chrisguindon** [comment]
@phkrief Sounds good! Please let us know if we need to make change or if we are good to push this live!

**Comment by phkrief** [comment]
IMHO, we are good to push. Let's wait few more days to get a feed back from
Susan and Marco.
Thanks again

Kind regards
*—*
Philippe Krief, PhD
Research Relations Director | Eclipse Foundation, Inc.
Eclipse Foundation <http://www.eclipse.org/>: The Platform for Open
Innovation and Collaboration
M: +33 (0)6 21 01 06 81


Annastr. 46, D-64673 Zwingenberg
Handelsregister: Darmstadt HRB 92821
Managing Directors: Mike Milinkovich, Gael Blondelle

**Comment by hansmuff2** [comment]
Hi all,

thanks for the update, looks great! Just three minor updates before go-live:

"Read more” is missing for the following projects:
	- PDP4E: https://www.pdp4e-project.eu/
	- Panorama: https://www.panorama-research.org/
	- SmartCLIDE: https://smartclide.eu/
	- FabOS: https://www.fab-os.org/

Can we do the list of projects in alphabetical order?

RobMoSys: Exchange the bullet points with this text:
"RobMoSys aims to coordinate the whole community’s best and consolidated efforts to realise a step-change towards a European ecosystem for open and sustainable industry-grade software development for robotics. The project develops model-driven methods and tools building on top of current code-centric robotics platforms, enabling interoperability between different robotics domains in an efficient and systematic way. A core part of the project is active community building and management to maximize synergies among robotics practitioners.”

**Comment by ericpoirier** [comment]
Hi Marco,

I updated the research page as per your comments

https://deploy-preview-4--eclipsefdn-research.netlify.com/

Let me know if there's anything else.

Thanks.

**Comment by chrisguindon** [comment]
//cc @hansmuff2

**Comment by phkrief** [comment]
Could you add the missing logo for SmartCLIDE, please?
![SmartClideRGBColor](https://user-images.githubusercontent.com/6196602/75017741-fd98e880-548d-11ea-8b15-e612d34d1165.png)

**Comment by ericpoirier** [comment]
> Could you add the missing logo for SmartCLIDE, please?
> ![SmartClideRGBColor](https://user-images.githubusercontent.com/6196602/75017741-fd98e880-548d-11ea-8b15-e612d34d1165.png)

Hi Philippe,

I added the SmartClide logo to the page.

Let me know if there's anything else.

Thanks.

**Comment by phkrief** [comment]
Hi @ericpoirier 
I think we are all set for this one.
Please update our webpage accordingly.

Thanks a lot for your work
Kind regards
-Philippe

**Comment by ericpoirier** [comment]
Hi Philippe,

Chris merged my patch and we should see the changes on the website in a few minutes.

Let me know if there's anything else.

Thanks.
