### ISSUE TITLE
Please add "Resources" section on eclipse.org/research

### ISSUE THREAD

**Issue by Ioana240** [EclipseFdn/eclipse.org-research#35]
Please add a "Resources" section with on eclipse.org/research.

Steps:

1. Go to eclipse.org/research
2. Add the "Resources" section between the "The Eclipse Foundation is a Partner in these Projects" section and the "Contact us" section.
3.The Resources section should contain the 4 "boxes", ie. Whitepaper, Factsheet, Case Study, Slide Deck like in the screenshot attached to this bug- reference point: the Resources section on eclipse.org/europe

Thank you!
Ioana

![Eclipseeurope](https://user-images.githubusercontent.com/61757816/93333560-c58b3580-f823-11ea-914b-1ddb888ed113.PNG)

**Comment by chrisguindon** [comment]
@Ioana240 We would like to finish the work that we are doing on /europe where you are asking us to add this new case study.

Once that issues is completed, we will work on getting this one done.

**Comment by chrisguindon** [comment]
@Ioana240 can you take a look at the work that @flora8984461 did so far for this?
https://deploy-preview-44--eclipsefdn-research.netlify.app/

Please let us know if need us to replace the content with something else.

**Comment by Ioana240** [comment]
Hi Yi and Chris,

It looks good to me, there is also the correct content in the section, I have no more suggestions to this. Thank you for your help with this mini-project!

-Ioana
