### ISSUE TITLE
When  an Eclipse project doesn't have a logo, it is not displayed properly in the research page

### ISSUE THREAD

**Issue by phkrief** [EclipseFdn/eclipse.org-research#42]
I'm trying to add a "friend" project to our list of Research projects: Eclipse Repairnator.
The project is pointing to itself to reference the associated Eclipse project:

> title: "Repairnator"
> date: 2020-03-11T14:40:29-04:00
> logo: ""
> tags: ["Automated Repair"]
> homepage: "https://www.eclipse.org/repairnator"
> facebook: ""
> linkedin: ""
> twitter: ""
> youtube: "https://youtu.be/sHkogNGyBSs"
> funding_bodies: []
> eclipse_projects: [**"technology.repairnator"**]
> project_type: running
> summary: "Open-source and open-innovation platform for automated program repair between academia and research"

The Research project page cannot display any logo. I was expecting it would display the Eclipse Incubation logo like an Eclipse project does. Can we fix that?

![image](https://user-images.githubusercontent.com/6196602/94525068-c6649400-0233-11eb-8b19-ebffc7ceb9d4.png)

Thx for your help

**Comment by chrisguindon** [comment]
@phkrief please do not assign my whole team to an issue.

**Comment by chrisguindon** [comment]
@phkrief I created https://bugs.eclipse.org/bugs/show_bug.cgi?id=567445 to set a default logo for projects without a logo. Your problem should be fixed on that bug is done.

**Comment by phkrief** [comment]
Thx a lot @chrisguindon

**Comment by phkrief** [comment]
Works ! Thx guys !!
