### ISSUE TITLE
Improve the layout / size of the Eclipse Logos in a Research project page

### ISSUE THREAD

**Issue by phkrief** [EclipseFdn/eclipse.org-research#48]
**Describe the bug**
The logo of an Eclipse logo looks really too big in a research project page:
Could we improve the layout of the icons:
![image](https://user-images.githubusercontent.com/6196602/96583312-cc9edb00-12dc-11eb-9ba2-b640a7b4e590.png)

I would expect to have the same size for both icons: the project icon and the Eclipse icon:
https://deploy-preview-47--eclipsefdn-research.netlify.app/project/repairnator/

We don't retrieve the same issue on this page:
https://deploy-preview-47--eclipsefdn-research.netlify.app/project/agile/

Thanks for your help

**Comment by flora8984461** [comment]
I am actually thinking about this issue, it can be solved once this PR https://github.com/EclipseFdn/eclipse.org-research/pull/46 is merged. If this PR is merged, that big project Logo will never exist, what do you think? @chrisguindon 🤔

**Comment by chrisguindon** [comment]
@flora8984461 +1 

It's now merged! @phkrief can you take a look and please re-open this issue if you need us to make more changes.
