### ISSUE TITLE
The website doesn't install properly

### ISSUE THREAD

**Issue by phkrief** [EclipseFdn/eclipse.org-research#58]
I tried to update a few files on my fork and wanted to test them locally. The npm install produced an error.
So I tried directly by cloning the main repo and I get the same error during the install process:

-------
npm install

> fsevents@1.2.13 install /Users/philippe/git/eclipse.org-research-origin/node_modules/fsevents
> node install.js

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Darwin 20.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/philippe/git/eclipse.org-research-origin/node_modules/fsevents
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 

> core-js@3.8.3 postinstall /Users/philippe/git/eclipse.org-research-origin/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> eclipsefdn-hugo-research@0.0.0 postinstall /Users/philippe/git/eclipse.org-research-origin
> NODE_ENV=production npm run production && npm run fetch_project

> eclipsefdn-hugo-research@0.0.0 production /Users/philippe/git/eclipse.org-research-origin
> NODE_ENV=production webpack --progress --config=node_modules/laravel-mix/setup/webpack.config.js

[webpack-cli] /Users/philippe/git/eclipse.org-research-origin/node_modules/laravel-mix/src/Mix.js:18
    static _primary = null;
                    ^

SyntaxError: Unexpected token =
    at new Script (vm.js:73:7)
    at NativeCompileCache._moduleCompile (/Users/philippe/git/eclipse.org-research-origin/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/Users/philippe/git/eclipse.org-research-origin/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/Users/philippe/git/eclipse.org-research-origin/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at module.exports (/Users/philippe/git/eclipse.org-research-origin/node_modules/laravel-mix/setup/webpack.config.js:2:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! eclipsefdn-hugo-research@0.0.0 production: `NODE_ENV=production webpack --progress --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the eclipsefdn-hugo-research@0.0.0 production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/philippe/.npm/_logs/2021-07-06T07_18_33_042Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! eclipsefdn-hugo-research@0.0.0 postinstall: `NODE_ENV=production npm run production && npm run fetch_project`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the eclipsefdn-hugo-research@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/philippe/.npm/_logs/2021-07-06T07_18_33_315Z-debug.log

-------

**To Reproduce**
1. Clone this repo
2. Execute npm install
3. Execute hugo server
4. Check the resulting website 

Did I miss something?

Thx a lot for your help

**Comment by chrisguindon** [comment]
`gyp ERR! node -v v10.9.0`

I think your issue is with your version of node-js. Can you try to upgrade to version v12?

**Comment by phkrief** [comment]
Dear Chris,
You were right.
It took me some time to upgrade and it works now.
Thx a lot
